# Perfil de Desarrollo
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  sql:
    init:
      mode: always
      
  h2:
    console:
      enabled: false

logging:
  level:
    com.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
  file:
    name: logs/ecommerce-dev.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always 